### ISSUE TITLE
Alchemy MVP TODO

### ISSUE THREAD

**Issue by TheShuEd** [crystallpunk-14/crystall-punk-14#140]
- [x] Solution management
  - [x] Big liquid storage (Vat)
  - [x] Portable large liquid container (Cauldron)
  - [x] liquid storage bottles of different sizes
- [x] Alchemy tools
  - [x] Solutions item extractor (mortar and pestle)
  - [x] Solutions heater (Alchemy furnace, Bonfire)
  - [x] Solutions concentration
- [x] Alchemy content
  - [x] Herbs collectable
  - [x] Potions: 
    - [x] Healing (brute)
    - [x] Poisons 
- [x] Progression 
  - [x] Roundstart role lock: Alchemy glasses 
- [ ] Furniture
  - [x] Glass potions cabinet
  - [ ] Alchemyst lock, key, doors
- [x] Roundstart role
  - [ ] Loadout clothing
