### ISSUE TITLE
MVP TODO: Part 2

### ISSUE THREAD

**Issue by TheShuEd** [crystallpunk-14/crystall-punk-14#178]
## Description

- [ ] Advanced melee fightting
- [ ] Activity - different game activities. Each with its own gameplay loop, in-round progression and roles.
  - [ ] Alchemy
  - [ ] Blacksmithing
  - [ ] Security
  - [ ] Adventurers
  - [ ] Cooking
  - [ ] Medical
  - [ ] Building
- [ ] Round structure
  - [ ] Town Portal - Latejoin connection, cryosleep round removal
  - [ ] Individual goals
  - [ ] "Traitor" gamemode
    - [ ] Shapeshifter antagonist
  - [ ] Round end???

**Comment by DocNITE** [comment]
Shapeshifter antagonist? There is exist some ref in docs?
